Discord:
    TOKEN: "MTAwMDMxMTczODYzOTU5NzY2OQ.G7szbs.tZk8N2AHRtqiXZhH6O_qDGpd-9vgr36zRzukeo"
    PREFIX: "dsb?"

SPOTIFY:
    CLIENT_ID: "32f03af242d34992993d6e7e87c3c852"
    CLIENT_SECRET: "2865f73d1f664e6581931f5b8ce1342c"
LAVALINK:
    HOST: "lavalink.net.dsb"
    PASSWORD: "www.lavalink.dsb"
    PORT: 888